name: "exp-dep"
repository: github.com/satandyh/trivy-plugin-explicit-dependency
version: "0.4.0"
usage: Scan filesystem and skip non-explicit dependencies
description: |-
  A Trivy plugin that scans the filesystem and skip all except packages in **/**/package.yaml files.
  Usage: trivy exp-dep -- [-h,--help] -p PROJECT_PATH [--global] [TRIVY OPTION]
platforms:
  - selector:
      os: linux
      arch: amd64
    uri: ./trivy-explicit-dependency
    bin: ./trivy-explicit-dependency
