name: "exp-dep"
repository: github.com/satandyh/trivy-plugin-explicit-dependency
version: "0.2.0"
usage: Scan filesystem and skip non-explicit dependencies
description: |-
  A Trivy plugin that scans the filesystem and skip all except packages in **/**/package.yaml files.
  Usage: trivy exp-dep PATH
platforms:
  - selector:
      os: linux
      arch: amd64
    uri: ./trivy-explicit-dependency
    bin: ./trivy-explicit-dependency
