[build]
target = "x86_64-unknown-linux-gnu"
rustflags = ['-C', 'target-feature=+crt-static']

[target.x86_64-unknown-linux-gnu]
rustflags = ['-C', 'target-feature=+crt-static']
linker = "clang"

[profile.release]
strip = true
lto = true
